name: Build new version of LIVE555 Proxy Server

on:
  push:
    tags:
      - "*"

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get-version
        run: echo "::set-output name=version::`echo ${{ github.ref }} | grep -Eo -m1 '[[:digit:]]{4}\.[[:digit:]]{2}\.[[:digit:]]{2}[[:alpha:]]?$' -`"
      - name: Setup Docker Buildx
        if: ${{ steps.get-version.outputs.version }}
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: ${{ steps.get-version.outputs.version }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Build & Push
        if: ${{ steps.get-version.outputs.version }}
        run: |
          docker buildx build \
            --platform linux/arm/v6,linux/arm/v7,linux/amd64 \
            --tag paradisi/live555-proxy-server:latest \
            --tag paradisi/live555-proxy-server:${{ steps.get-version.outputs.version }} \
            --push .
