name: Check for new version of LIVE555 Media Server

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check-for-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for new version
        id: check-for-new-version
        timeout-minutes: 5
        run: |
          if [ $(curl -s -N http://www.live555.com/liveMedia/public/live555-latest-md5.txt | cmp -s live555-latest-md5.txt) ];
          then
            echo "::set-output name=available::false"
          else
            echo "::set-output name=available::true"
          fi
      - name: Download changelog
        if: ${{ steps.check-for-new-version.outputs.available }}
        timeout-minutes: 5
        run: |
          wget -O changelog.txt http://www.live555.com/liveMedia/public/changelog.txt
          wget -O live555-latest-md5.txt http://www.live555.com/liveMedia/public/live555-latest-md5.txt
