name: Check for new version of LIVE555 Media Server

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check-for-new-version:
    runs-on: ubuntu-latest
    outputs:
      available: ${{ steps.check-for-new-version.outputs.available }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for new version
        timeout-minutes: 5
        run: |
          if [ $(curl -s -N http://www.live555.com/liveMedia/public/live555-latest-md5.txt | cmp -s live555-latest-md5.txt) ];
          then
            echo "::set-output name=available::false"
          else
            echo "::set-output name=available::true"
          fi
  download-changelog:
    runs-on: ubuntu-latest
    needs: check-for-new-version
    steps:
      - run: echo ${{needs.check-for-new-version.outputs.available}}
      - name: Download changelog
        timeout-minutes: 5
        run: wget http://www.live555.com/liveMedia/public/changelog.txt
