name: Check for new version of LIVE555 Media Server

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check-for-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new version
        timeout-minutes: 5
        run: if [ $(curl --silent http://www.live555.com/liveMedia/public/live555-latest-md5.txt | cmp --silent live555-latest-md5-new.txt) ]; then echo "::set-output name=new::false"; else echo "::set-output name=new::true"; fi
