name: CI

on:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: live555-md5
